import express from 'express';
import { upload } from '../config/cloudinary.js';
import requireAuth from '../middleware/authMiddleware.js';
import ApiResponse from '../utils/apiResponse.js';

const router = express.Router();

/**
 * @route   POST /api/upload
 * @access  Private (Requires login)
 * @desc    Uploads a single image to Cloudinary and returns the URL.
 *          The frontend must send a multipart/form-data request with the file under the key 'image'.
 */
router.post('/', requireAuth, upload.single('image'), (req, res) => {
  if (!req.file) {
    return res.status(400).json(new ApiResponse(400, "No image file uploaded"));
  }
  
  // Return the secure URL generated by Cloudinary
  return res.status(200).json(new ApiResponse(200, "Image uploaded successfully", {
    url: req.file.path,
    publicId: req.file.filename
  }));
});

export default router;
